set(TARGET llama-mtp-worker-server)
add_executable(${TARGET} llama-mtp-worker-server.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE llama-common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)

set(TARGET llama-remote-mtp-e2e-bench)
add_executable(${TARGET} llama-remote-mtp-e2e-bench.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE llama-common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)

set(TARGET llama-mtp-rtt-client)
add_executable(${TARGET} llama-mtp-rtt-client.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE llama-common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)

if (WIN32)
    target_link_libraries(llama-mtp-worker-server PRIVATE ws2_32)
    target_link_libraries(llama-remote-mtp-e2e-bench PRIVATE ws2_32)
    target_link_libraries(llama-mtp-rtt-client PRIVATE ws2_32)
endif()

set(TARGET llama-remote-mtp-fork-bench)
add_executable(${TARGET} llama-remote-mtp-fork-bench.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE llama-common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)
